### ISSUE TITLE
Support for other PAM formats 

### ISSUE THREAD

**Issue by eratio08** [baslr/node-ppm-bin#1]
Could you add support for Portable Bitmap (PBM) and Portable Graymap (PGM)?

**Comment by baslr** [comment]
Hi @eratio08,

you mean PBM, PGM to PNG? I can look at it. Can paste some example files for pgm and pbm? Than I will implement it.

Kind regards

**Comment by eratio08** [comment]
yeah right :) sorry mixed that up

that would be great!

**Comment by eratio08** [comment]
Hey @baslr,

yeah right for a pure JavaScript implementation - right now I'm using the pnmtopng from netpbm.

a sample file could be found here http://www.fileformat.info/format/pbm/egff.htm - http://www.fileformat.info/format/pbm/sample/index.htm

Thank you :)

**Comment by baslr** [comment]
Thanks for the link. What you need first? Binary oder ASCII support?

**Comment by eratio08** [comment]
The node buffer is hex formated or isn't it?
Well I guess I don't get your question

EDIT:
I guess ASCII 
magic number P4,P5,P6

**Comment by baslr** [comment]
The file format that stores ppm, pbm or pgm is either encoded binary or ascii. if its encoded ascii you literally can create a image in your favorite text editor and enter ascii letters. fate it and you can open it in say gimp as an image.

**Comment by eratio08** [comment]
Both would be great but in my case the images are ASCII encoded. -> P4, P5, P6

**Comment by baslr** [comment]
Okay, I will have a look at it tomorrow.
